//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgixshuaMediaLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_Games
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Edition { get; set; }
        public string Platform { get; set; }
        public int Year { get; set; }
    }
}
